server:
  port: ${CONFIG_SERVICE_PORT:8888}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    preferIpAddress: true

spring:
    application:
        name: blockchain-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/sergio11/trust_certification_system_blockchain_config.git
                    default-label: main
