server:
  port: ${CONFIG_SERVICE_PORT:8888}
spring:
    application:
        name: blockchain-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/sergio11/trust_certification_system_blockchain_config.git
                    default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true