server:
  port: ${CONFIG_SERVICE_PORT:8888}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    preferIpAddress: true

spring:
    application:
        name: blockchain-config-server
    bus:
      enabled: true
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka:9092
                    auto-create-topics: true
                    configuration.auto.offset.reset: latest
        config:
            server:
                git:
                    uri: https://github.com/sergio11/trust_certification_system_blockchain_config.git
                    default-label: main

