spring:
  application:
    name: blockchain-processor
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  cloud:
    config:
        import-check:
            enabled: false
        discovery:
            enabled: true
            serviceId: blockchain-config-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka/
  instance:
    preferIpAddress: true
