version: '3.6'

services:
  eth_netstats:
    image: kamael/eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"
  eth_bootstrap:
    build: eth_geth
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - eth_netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --ipcpath=~/.ethereum/ipc --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3,txpool,personal" --rpccorsdomain="*" --networkid=85 --rpc --rpcaddr="0.0.0.0" --txpool.globalslots=250000 --txpool.globalqueue=50000'
    volumes:
      - ./eth_geth/data/keystore:/root/.ethereum/keystore:rw
      - ./eth_geth/data/node_bootstrap:/root/.ethereum/devchain/geth:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth_node_1:
    build: eth_geth
    restart: on-failure
    container_name: eth_geth_1
    hostname: eth_geth_1
    links:
      - eth_bootstrap
      - eth_netstats
    entrypoint: /root/start.sh
    volumes:
      - ./eth_geth/data/keystore:/root/.ethereum/keystore:rw
      - ./eth_geth/data/node_1:/root/.ethereum/devchain/geth:rw
    command: '--datadir=~/.ethereum/devchain --ipcpath=~/.ethereum/ipc --rpccorsdomain="*" --networkid=85 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --mine --miner.threads=2 --miner.etherbase=0xE545f3b554175BABcBeF152D4516Ff90455095EE'
  eth_node_2:
    build: eth_geth
    restart: on-failure
    container_name: eth_geth_2
    hostname: eth_geth_2
    links:
      - eth_bootstrap
      - eth_netstats
    entrypoint: /root/start.sh
    volumes:
      - ./eth_geth/data/keystore:/root/.ethereum/keystore:rw
      - ./eth_geth/data/node_2:/root/.ethereum/devchain/geth:rw
    command: '--datadir=~/.ethereum/devchain --ipcpath=~/.ethereum/ipc --rpccorsdomain="*" --networkid=85 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --mine --miner.threads=2 --miner.etherbase=0xE545f3b554175BABcBeF152D4516Ff90455095EE'
  eth_node_3:
    build: eth_geth
    restart: on-failure
    container_name: eth_geth_3
    hostname: eth_geth_3
    links:
      - eth_bootstrap
      - eth_netstats
    entrypoint: /root/start.sh
    volumes:
      - ./eth_geth/data/keystore:/root/.ethereum/keystore:rw
      - ./eth_geth/data/node_3:/root/.ethereum/devchain/geth:rw
    command: '--datadir=~/.ethereum/devchain --ipcpath=~/.ethereum/ipc --rpccorsdomain="*" --networkid=85 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'
  eth_node_4:
    build: eth_geth
    restart: on-failure
    container_name: eth_geth_4
    hostname: eth_geth_4
    links:
      - eth_bootstrap
      - eth_netstats
    entrypoint: /root/start.sh
    volumes:
      - ./eth_geth/data/keystore:/root/.ethereum/keystore:rw
      - ./eth_geth/data/node_4:/root/.ethereum/devchain/geth:rw
    command: '--datadir=~/.ethereum/devchain --ipcpath=~/.ethereum/ipc --rpccorsdomain="*" --networkid=85 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303"'