package com.dreamsoftware.tcs.persistence.nosql.entity;

/**
 *
 * @author ssanchez
 */
public enum EmailTypeEnum {
    COMPLETE_ACCOUNT_DELETION,
    USER_ACTIVATED,
    CONFIRM_PASSWORD_CHANGE,
    RESET_PASSWORD,
    USER_PENDING_VALIDATION,
    CA_ENABLED,
    CA_DISABLED,
    CERTIFICATE_DISABLED,
    CERTIFICATE_ENABLED,
    CERTIFICATE_RENEWED,
    CERTIFICATE_REQUEST_ACCEPTED,
    CERTIFICATE_REQUEST_REJECTED,
    CERTIFICATE_VISIBILITY_CHANGED,
    CERTIFICATE_GENERATED,
    ISSUE_CERTIFICATE_REQUEST,
    COURSE_DISABLED,
    COURSE_ENABLED,
    NEW_COURSE_REGISTRATION_REQUESTED,
    CERTIFICATION_COURSE_REGISTERED,
    USER_ORDER_COMPLETED;
}
