version: '3.6'

# Volumes
volumes:
  zookeeper-data:
    driver: local
  zookeeper-log:
    driver: local
  kafka-data:
    driver: local

# Networks
networks:
  tcs_network:
    name: tcs_network


services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - tcs_network

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    volumes:
      - kafka-data:/var/lib/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_NUM_PARTITIONS: 12
      KAFKA_COMPRESSION_TYPE: gzip
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_JMX_PORT: 9091
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    links:
      - zookeeper
    networks:
      - tcs_network

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
    ports:
      - 8088:8080
    links:
      - kafka
    networks:
      - tcs_network


  vault:
    image: vault:latest
    restart: on-failure
    container_name: vault
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.json
    networks:
      - tcs_network

  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devroot
      - MONGO_INITDB_ROOT_PASSWORD=devroot
      - MONGO_INITDB_DATABASE=trustcertificationsystem
    networks:
      - tcs_network


  # Web-based MongoDB admin interface, written with Node.js and express
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: on-failure
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=devroot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=devroot
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    depends_on:
      - mongo
    ports:
      - "8083:8081"
    networks:
      - tcs_network

  # Trust Certification System Discovery Server
  tcs_discovery_server:
    image: ssanchez11/trust_certification_system_discovery_server:0.0.1-SNAPSHOT
    container_name: tcs-discovery-server
    ports:
      - "8761:8761"
    networks:
      - tcs_network

  # Trust Certification System Monitor Server
  tcs_monitor_server:
    image: ssanchez11/trust_certification_system_monitor_server:0.0.1-SNAPSHOT
    container_name: bc-monitor-server
    ports:
      - "8060:8060"
    environment:
      - SERVICE_REGISTRY_HOST=tcs-discovery-server
      - JASYPT_ENCRYPTOR_PASSWORD=a{uL#t#jkp,Kd[9{
    networks:
      - tcs_network

  # Trust Certification System Config Server
  tcs_config_server:
    image: ssanchez11/trust_certification_system_config_server:0.0.1-SNAPSHOT
    container_name: tcs-config-server
    networks:
      - tcs_network
    ports:
      - "8081:8080"
    environment:
      - SERVICE_REGISTRY_HOST=tcs-discovery-server

  # Trust Certification System Gateway API
  tcs_gateway_api:
    image: ssanchez11/trust_certification_system_gateway_api:0.0.1-SNAPSHOT
    container_name: tcs-gateway-api
    volumes:
      - ./wallets:/opt/wallets
    ports:
      - "8080:8080"
    networks:
      - tcs_network
    environment:
      - SERVICE_REGISTRY_HOST=tcs-discovery-server
      - JASYPT_ENCRYPTOR_PASSWORD=a{uL#t#jkp,Kd[9{

  # Trust Certification System Certificate Events Processor
  tcs_certificate_events_processor:
    image: ssanchez11/trust_certification_system_certificate_events_processor:0.0.1-SNAPSHOT
    container_name: tcs-certificate-events-processor
    volumes:
      - ./wallets:/opt/wallets
    networks:
      - tcs_network
    environment:
      - SERVICE_REGISTRY_HOST=tcs-discovery-server
      - JASYPT_ENCRYPTOR_PASSWORD=a{uL#t#jkp,Kd[9{

  # Trust Certification System User Events Processor
  tcs_user_events_processor:
    image: ssanchez11/trust_certification_system_user_events_processor:0.0.1-SNAPSHOT
    container_name: tcs-user-events-processor
    volumes:
      - ./wallets:/opt/wallets
    networks:
      - tcs_network
    environment:
      - SERVICE_REGISTRY_HOST=tcs-discovery-server
      - JASYPT_ENCRYPTOR_PASSWORD=a{uL#t#jkp,Kd[9{

  # Trust Certification System Course Events Processor
  tcs_course_events_processor:
    image: ssanchez11/trust_certification_system_course_events_processor:0.0.1-SNAPSHOT
    container_name: tcs-course-events-processor
    volumes:
      - ./wallets:/opt/wallets
    networks:
      - tcs_network
    environment:
      - SERVICE_REGISTRY_HOST=tcs-discovery-server
      - JASYPT_ENCRYPTOR_PASSWORD=a{uL#t#jkp,Kd[9{