package com.dreamsoftware.tcs.web.controller.course;

import com.dreamsoftware.tcs.web.core.IResponseCodeTypes;

/**
 * Certification Course Response Code Enum
 *
 * @author ssanchez
 */
public enum CertificationCourseResponseCodeEnum implements IResponseCodeTypes {
    CERTIFICATION_COURSE_DETAIL(300L),
    CERTIFICATION_COURSE_FAILED(301L),
    CERTIFICATION_COURSE_ENABLED(302L),
    ENABLE_CERTIFICATION_COURSE_FAILED(303L),
    CERTIFICATION_COURSE_DISABLED(304L),
    DISABLE_CERTIFICATION_COURSE_FAILED(305L),
    SAVE_CERTIFICATION_COURSE(306L),
    SAVE_CERTIFICATION_COURSE_FAILED(307L),
    GET_CERTIFICATION_COURSE_DETAIL_FAILED(308L),
    CERTIFICATION_COURSE_CAN_BE_ISSUED(309L),
    CERTIFICATION_COURSE_CANNOT_BE_ISSUED(310L),
    CHECK_CERTIFICATION_COURSE_CAN_BE_ISSUED_FAILED(311L),
    CERTIFICATION_COURSE_DELETED(313L),
    DELETE_CERTIFICATION_COURSE_FAILED(314L),
    PARTIAL_CERTIFICATION_COURSE_UPDATE(315L),
    PARTIAL_CERTIFICATION_COURSE_UPDATE_FAILED(316L),
    GET_ALL_CERTIFICATION_COURSES(317L),
    GET_ALL_CERTIFICATION_COURSES_FAILED(318L),
    GET_CERTIFICATION_COURSES_BY_CA(319L),
    GET_CERTIFICATION_COURSES_BY_CA_FAILED(320L),
    SAVE_CERTIFICATION_COURSE_EDITION_SUCCESSFULLY(321L),
    SAVE_CERTIFICATION_COURSE_EDITION_FAILED(322L),
    CERTIFICATION_COURSE_EDITION_ENABLED(323L),
    ENABLE_CERTIFICATION_COURSE_EDITION_FAILED(324L),
    CERTIFICATION_COURSE_EDITION_DISABLED(325L),
    DISABLE_CERTIFICATION_COURSE_EDITION_FAILED(326L),
    CERTIFICATION_COURSE_EDITION_DELETED(327L),
    DELETE_CERTIFICATION_COURSE_EDITION_FAILED(328L),
    PARTIAL_CERTIFICATION_COURSE_EDITION_UPDATED(329L),
    PARTIAL_CERTIFICATION_COURSE_EDITION_UPDATE_FAILED(330L),
    SEARCH_CERTIFICATION_COURSES_SUCCESSFULLY(331L),
    SEARCH_CERTIFICATION_COURSES_FAILED(332L),
    CERTIFICATION_COURSE_CAN_BE_RENEWED(333L),
    CERTIFICATION_COURSE_CANNOT_BE_RENEWED(334L),
    CHECK_CERTIFICATION_COURSE_CAN_BE_RENEWED_FAILED(335L),
    COURSE_EDITION_ENROLLMENT_REQUEST_COMPLETED(326L),
    COURSE_EDITION_ENROLLMENT_REQUEST_FAILED(327L),
    GET_ENROLLMENT_QT_FAILED(328L);

    private final Long code;
    public static final String CATEGORY_NAME = "CERTIFICATION_COURSE";

    private CertificationCourseResponseCodeEnum(Long code) {
        this.code = code;
    }

    @Override
    public Long getResponseCode() {
        return code;
    }

    @Override
    public String getCategoryName() {
        return CATEGORY_NAME;
    }

    @Override
    public String getCodeName() {
        return name();
    }

}
