spring:
  application:
    name: blockchain_gateway_service
  data:
    mongodb:
        authentication-database: admin
        database: trustcertificationsystem
        host: mongo
        port: 27017
        username: ENC(vb0mlnK7rEnJyAw459NoSg==)
        password: ENC(dT+5AMBOTacnNnBTqxt12g==)
  cloud:
    stream:
        kafka:
            binder:
                brokers: kafka:9092
                auto-create-topics: true
                configuration.auto.offset.reset: latest
        bindings:
            caInitialFunds-out-0:
                destination: CA-initial-funds-v1
            certificationCourseRegistration-out-0:
                destination: CC-registration-v1
        function:
            autodetect: false
  # Mail
  # output of emails
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(iWAhNuq66KM19C9NnrN5sE3t2Y6cxGVuFh4Ouyj6Xh3NBXA7V4NN1Q==)
    password: ENC(+clt1ygZG1HTJuancbLk9DGr9P0JHhOa+VEFBjAi4lo=)
    properties:
        mail:
            smtp:
                auth: true
                starttls.enable: true
                ssl.trust: smtp.gmail.com
                connectiontimeout: 5000
                timeout: 5000
                writetimeout: 5000

# JWT
jwt:
    token:
        header: Authorization
        secret: ENC(jE/+2/YpjTKkFpHbFlNzIVgpzHvwPhWo1+12ZaD3WLHGx5Ew+X2kvocuxV0qXp7Q)
        expiration: 604800
    route:
        authentication:
            path: /auth
            refresh: refresh

# REST
api:
    base:
        path: /api/
    version: v1

# i18n Config
i18n:
    paramname: lang
    default.locale: en_GB
    locale.supported: es_ES,en_GB

# Mail Properties
mail:
    templates:
        base.dir: mail/templates/
    resources:
        base.dir: mail/resources/
    registration.success.template.name: mail_template_registration_success
    confirm.account.activation.template.name: mail_template_confirm_account_activation
    from: ENC(2fhT/KBRBQbae36mvdNRWizBRsmWPfNtHKGVkiUDphs7DDGJz7EPcA==)

## Trust Certification System Props
trust:
    certification:
        system:
            chain-id: 85
            wallet-directory: /opt/wallets
            client-address: http://bootstrap:8545
            root-public-key: "0xE545f3b554175BABcBeF152D4516Ff90455095EE"
            root-private-key: ENC(7k5dAObOTy1arUeaWbSG1mldiWDR/3mIJHqqRnXivkXaTpjYkYMNTfy8Ivktio6I2qnT+QK6DetaWpIw3AZqVRhBoPRORiCcNGYwJZE5ly0=)
            gas-price: 1000000000
            gas-limit: 993613
            token-management-contract-address: "0x4e690116b461DB7E23f78E991F94dB8Eb1E26B55"
            certification-authority-contract-address: "0x801db69e6D2dC0ED1A7Dac9B0be5D0921Dd4395C"
            certification-course-contract-address: "0x6dF5B51DA5587611eAFd0AA7727f0a8CAf9B6B7C"
            trust-certification-contract-address: "0xc9F57EA9418190f14bbF2d00E776462105ffe677"
            trust-ether-faucet-contract-address: "0x8F3FD73CbF7081D4E764b4ff7708cBB62950D301"

## SFTP Config
sftp:
    hostname: 192.168.1.39
    port: 2222
    username: ethsftp
    password: ethsftp00
    remoteFolder: keystore/

##### Configuration for account management ####
task:
    account:
        delete:
             ## Task to remove expired password reset token
            expired.tokens: 15 10 * * * ?
            ## Task to remove inactive accounts
            ## At second :15 of minute :10 of every hour
            unactivated.accounts: 15 10 * * * ?
        ## Task to cancel account removal processes
        ## At second :15 of minute :20 of every hour
        cancel.account.deletion.proccess: 15 20 * * * ?
        ## Task for forwarding failed emails
        ## At second :00, every 5 minutes starting at minute :00, of every hour
        unsuccessful.mail.forwarding: 0 0/5 * * * ?
        ## Number of emails to be forwarded
        unsuccessful.mail.forwarding.number.of.emails.to.forward: 10


######## Encryption Configuration #####
jasypt:
    encryptor:
        password: a{uL#t#jkp,Kd[9{

logging.level:
  org.springframework.cloud: DEBUG
  org.springframework.security: DEBUG
  com.dreamsoftware.blockchaingateway: DEBUG
  logging.level.org.web3j.protocol.http: TRACE

server.port: 8080